### ISSUE TITLE
Error "GetPeerAddress"

### ISSUE THREAD

**Issue by Pyreweb** [UniversalAvenue/TiCrosswalk#9]
Hi,

I have a new error, but it doesn't seems to be dramatic; It just repeat a lot.
```
[ERROR] chromium: [ERROR:unix_domain_client_socket_posix.cc(101)] Not implemented reached in virtual int net::UnixDomainClientSocket::GetPeerAddress(net::IPEndPoint*) const
```

**Comment by mrlundis** [comment]
This is an issue in the crosswalk build of chromium. It will hopefully be fixed when I upgrade the bundled xwalk binary.

**Comment by Pyreweb** [comment]
Ok, thanks, I'll wait for it

**Comment by mrlundis** [comment]
@Pyreweb I've released an updated version of the module, please feel fre to try it out!

**Comment by Pyreweb** [comment]
Tested, and the error disappeared !

The only one I got now, at the start of a Crosswalk (just before the ``[WARN]  BuiltinXWalkExtension: Failed to read JS API file: jsapi/presentation_api.js``), is :
```
[ERROR] chromium: [ERROR:unix_domain_server_socket_posix.cc(106)] Not implemented reached in virtual int net::UnixDomainServerSocket::GetLocalAddress(net::IPEndPoint*) const
```
Which doesn't seems to do anything excepted get logged (like the GetPeer one).

**Comment by mrlundis** [comment]
Great! :smile:
